# Generated by Django 4.0.3 on 2022-03-27 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('acft_range', models.IntegerField()),
                ('fuel_consumption', models.IntegerField()),
                ('fuel_capacity', models.IntegerField()),
                ('avg_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICAO', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('iso_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fob', models.IntegerField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.aircraft')),
                ('arrival_apt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_apt_id', to='viewer.airport')),
                ('departure_apt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_apt_id', to='viewer.airport')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('waypoints', models.ManyToManyField(blank=True, null=True, to='viewer.waypoint')),
            ],
        ),
    ]
