# Generated by Django 4.0.3 on 2022-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_aircraft_fuel_capacity_flightplan_fob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='waypoints',
            field=models.ManyToManyField(null=True, to='viewer.waypoint'),
        ),
    ]
