# Generated by Django 4.0.3 on 2022-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='waypoints',
            field=models.ManyToManyField(blank=True, null=True, to='viewer.waypoint'),
        ),
    ]
